version: '3'
services:
  adjective:
    build: adjective
    image: adjective
  noun:
    build: noun
    image: noun
  insult:
    build: insult
    image: insult
    ports:
    - "8081:80"
    links:
    - adjective
    - noun
  ui:
    build: ui
    image: ui
    ports:
    - "8080:8080"
    links:
    - insult
