apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: insult-configmaps
metadata:
  annotations:
    description: A template for creating configmaps for the Elizabethan Insult app
    iconClass: icon-vertx
    openshift.io/display-name: Vert.x App (k8s API)
    tags: vertx,http,k8s,kubernetes
  name: insult-configmaps
objects:
- apiVersion: v1
  data:
    http: |-
      {
          "port": 8080,
          "host": "0.0.0.0"
      }
  kind: ConfigMap
  metadata:
    name: adjective-config
- apiVersion: v1
  data:
    http: |-
      {
          "port": 8080,
          "host": "0.0.0.0"
      }
  kind: ConfigMap
  metadata:
    name: noun-config
- apiVersion: v1
  data:
    noun: |-
      {
          "port": 8080,
          "host": "noun-app"
      }
    adjective: |-
      {
          "port": 8080,
          "host": "adjective-app"
      }
    http: |-
      {
        "port": 8080,
        "host": "0.0.0.0",
        "cors": "https?://(.*\\.rht-labs\\.com)(:[0-9]*)?(/.*)?"
      }
  kind: ConfigMap
  metadata:
    name: insult-config
- apiVersion: v1
  data:
    settings.js: |-
      var loc_proto = window.location.protocol;
      var loc_host = window.location.hostname.replace(/^ui/, 'insult');
      var loc_port = window.location.port;

      if (loc_port === "") {
          window.base_url = loc_proto + "//" + loc_host;
      } else {
          window.base_url = loc_proto + "//" + loc_host + ":" + loc_port;
      }

