---
openshift_cluster_content:
- object: projectrequest
  content:
  - name: ci-cd
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ inventory_dir }}/../params/projectrequests/ci-cd"
    tags:
    - projects
  - name: dev
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ inventory_dir }}/../params/projectrequests/dev"
    tags:
    - projects
  - name: demo
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ inventory_dir }}/../params/projectrequests/demo"
    tags:
    - projects
- object: imagestreams
  content:
  - name: nginx-image-stream
    template: "{{ inventory_dir }}/../openshift-templates/imagestream/template.yaml"
    params: "{{ inventory_dir }}/../params/nginx-image-stream/import"
    namespace: rhoar-ci-cd
  - name: jenkins-37-image-stream
    template: "{{ inventory_dir }}/../openshift-templates/imagestream/template.yaml"
    params: "{{ inventory_dir }}/../params/jenkins-37-image-stream/import"
    namespace: rhoar-ci-cd
- object: ci-cd-builds
  content:
  - name: jenkins-s2i
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-s2i-build/template.yaml"
    params: "{{ inventory_dir }}/../params/jenkins/build"
    namespace: rhoar-ci-cd
    tags:
    - jenkins
  - name: jenkins-slave-ansible
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/../params/jenkins-slave-ansible/build"
    namespace: rhoar-ci-cd
    tags:
    - jenkins-slaves
  - name: jenkins-slave-mvn
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/../params/jenkins-slave-mvn/build"
    namespace: rhoar-ci-cd
    tags:
    - jenkins-slaves
  - name: jenkins-slave-npm
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/../params/jenkins-slave-npm/build"
    namespace: rhoar-ci-cd  
    tags:
    - jenkins-slaves
  - name: jenkins-slave-zap
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/../params/jenkins-slave-zap/build"
    namespace: rhoar-ci-cd
    tags:
    - jenkins-slaves
  - name: tool-box
    template: "{{ inventory_dir }}/../openshift-templates/docker-build/template.yaml"
    params: "{{ inventory_dir }}/../params/tool-box/build"
    namespace: rhoar-ci-cd
    tags:
      - tool-box
- object: ci-cd-deployments
  content:
  - name: jenkins-ephemeral
    template: openshift//jenkins-ephemeral
    params: "{{ inventory_dir }}/../params/jenkins/deploy"
    namespace: rhoar-ci-cd
    tags:
    - jenkins
  - name: nexus
    template: "{{ inventory_dir }}/../openshift-templates/nexus/template.json"
    params: "{{ inventory_dir }}/../params/nexus/deploy"
    namespace: rhoar-ci-cd
    tags:
    - nexus
  - name: sonarqube
    template: "{{ inventory_dir }}/../openshift-templates/sonarqube/template.json"
    params: "{{ inventory_dir }}/../params/sonarqube/build-and-deploy"
    namespace: rhoar-ci-cd
    tags:
    - sonar
  - name: sonarqube-postgresql
    template: "openshift//postgresql-persistent"
    params: "{{ inventory_dir }}/../params/sonarqube/postgresql"
    namespace: rhoar-ci-cd
    tags:
    - sonar
- object: app-builds
  content:
  - name: adjective-build
    template: "{{ inventory_dir }}/../openshift-templates/s2i-app-build/template-no-secrets.json"
    params: "{{ inventory_dir }}/../params/adjective-app/build"
    namespace: rhoar-ci-cd
  - name: noun-build
    template: "{{ inventory_dir }}/../openshift-templates/s2i-app-build/template-no-secrets.json"
    params: "{{ inventory_dir }}/../params/noun-app/build"
    namespace: rhoar-ci-cd
  - name: insult-build
    template: "{{ inventory_dir }}/../openshift-templates/s2i-app-build/template-no-secrets.json"
    params: "{{ inventory_dir }}/../params/insult-app/build"
    namespace: rhoar-ci-cd
  - name: ui-build
    template: "{{ inventory_dir }}/../openshift-templates/s2i-app-build/template-no-secrets.json"
    params: "{{ inventory_dir }}/../params/ui-app/build"
    namespace: rhoar-ci-cd
- object: dev-stage
  content:
  - name: noun-app
    template: "{{ inventory_dir }}/../openshift-templates/http-app/template.json"
    params: "{{ inventory_dir }}/../params/noun-app/deploy_dev"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: adjective-app
    template: "{{ inventory_dir }}/../openshift-templates/http-app/template.json"
    params: "{{ inventory_dir }}/../params/adjective-app/deploy_dev"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: insult-app
    template: "{{ inventory_dir }}/../openshift-templates/http-app/template.json"
    params: "{{ inventory_dir }}/../params/insult-app/deploy_dev"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: insult-ui
    template: "{{ inventory_dir }}/../openshift-templates/http-app/template.json"
    params: "{{ inventory_dir }}/../params/ui-app/deploy_dev"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/noun-app/fabric8_dev"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/adjective-app/fabric8_dev"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/insult-app/fabric8_dev"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/ui-app/fabric8_dev"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/noun-app/fabric8_demo"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/adjective-app/fabric8_demo"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/insult-app/fabric8_demo"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/ui-app/fabric8_demo"
    namespace: rhoar-dev
    tags:
    - insult-app
- object: demo-stage
  content:
  - name: noun-app
    template: "{{ inventory_dir }}/../openshift-templates/http-app/template.json"
    params: "{{ inventory_dir }}/../params/noun-app/deploy_dev"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: adjective-app
    template: "{{ inventory_dir }}/../openshift-templates/http-app/template.json"
    params: "{{ inventory_dir }}/../params/adjective-app/deploy_dev"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: insult-app
    template: "{{ inventory_dir }}/../openshift-templates/http-app/template.json"
    params: "{{ inventory_dir }}/../params/insult-app/deploy_dev"
    namespace: rhoar-dev
    tags:
    - insult-app
  - name: insult-ui
    template: "{{ inventory_dir }}/../openshift-templates/http-app/template.json"
    params: "{{ inventory_dir }}/../params/ui-app/deploy_dev"
    namespace: rhoar-dev
    tags:
    - insult-app