swagger: '2.0'
info:
  description: Adjective API for Elizabethan Insult Generator Microservices
  version: 1.0.0
  title: Elizabethan Adjectives Service
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /api/v1
tags:
  - name: adjective
    description: An Elizabethan derrogatory adjective
schemes:
  - http
  - https
paths:
  /adjective:
    get:
      tags:
        - adjective
      summary: Get an Adjective
      description: ''
      operationId: getAdjective
      produces:
        - text/plain
      responses:
        '200':
          description: OK
    post:
      tags:
        - adjective
      summary: Add an adjective
      description: ''
      operationId: addAdjective
      consumes:
        - text/plain
      produces:
        - text/plain
      responses:
        '202':
          description: Accepted
        '500':
          description: Server error
  '/adjective/{adjective}':
    delete:
      tags:
        - adjective
      summary: Delete an adjective
      description: Delete the adjective specified in the path
      operationId: deleteAdjective
      parameters:
        - name: adjective
          in: path
          description: The adjective to be deleted
          required: true
          type: string
      responses:
        '204':
          description: Deleted
        '403':
          description: Forbidden
        '404':
          description: Not found
