---
openshift_cluster_content:
- galaxy_requirements: "{{ inventory_dir }}/../galaxy_requirements.yml"
- object: projectrequest
  content:
  - name: ci-cd
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ inventory_dir }}/../params/projectrequests/ci-cd"
    tags:
    - projects
  - name: dev
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ inventory_dir }}/../params/projectrequests/dev"
    tags:
    - projects
  - name: demo
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ inventory_dir }}/../params/projectrequests/demo"
    tags:
    - projects
- object: ci-cd-builds
  content:
  - name: jenkins-s2i
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-s2i-build/template.yaml"
    params: "{{ inventory_dir }}/../params/jenkins/build"
    namespace: rhoar-vertx-ci-cd
    tags:
    - jenkins
  - name: jenkins-slave-mvn
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/../params/jenkins-slave-mvn/build"
    namespace: rhoar-vertx-ci-cd
    tags:
    - jenkins-slaves
    - mvn-slave
  - name: jenkins-slave-zap
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/../params/jenkins-slave-zap/build"
    namespace: rhoar-vertx-ci-cd
    tags:
    - jenkins-slaves
    - zap-slave
- object: ci-cd-deployments
  content:
  - name: sonarqube
    template: "{{ inventory_dir }}/../openshift-templates/sonarqube/template.yaml"
    params: "{{ inventory_dir }}/../params/sonarqube/build-and-deploy"
    namespace: rhoar-vertx-ci-cd
    tags:
    - sonar
  - name: maven-cache-volume
    template: "{{ inventory_dir }}/../openshift-templates/mvn-cache-pv/template.yaml"
    params: "{{ inventory_dir }}/../params/maven-cache-volume/deploy"
    namespace: rhoar-vertx-ci-cd
    tags:
    - jenkins
  - name: sonarqube-postgresql
    template: "openshift//postgresql-persistent"
    params: "{{ inventory_dir }}/../params/sonarqube/postgresql"
    namespace: rhoar-vertx-ci-cd
    tags:
    - sonar
  - name: jenkins-persistent
    template: "{{ inventory_dir }}/../openshift-templates/jenkins/jenkins-persistent-template.yaml"
    params: "{{ inventory_dir }}/../params/jenkins/deploy"
    namespace: rhoar-vertx-ci-cd
    tags:
    - jenkins
  - name: nexus
    template: "{{ inventory_dir }}/../openshift-templates/nexus/template.json"
    params: "{{ inventory_dir }}/../params/nexus/deploy"
    namespace: rhoar-vertx-ci-cd
    tags:
    - nexus
    post_steps:
    - role: "rhoar-vertx/roles/configure-nexus"
- object: app-builds
  content:
  - name: adjective-app-build
    template: "{{ inventory_dir }}/../openshift-templates/s2i-app-build/template-no-secrets.json"
    params: "{{ inventory_dir }}/../params/adjective-app/build"
    namespace: rhoar-vertx-ci-cd
  - name: noun-app-build
    template: "{{ inventory_dir }}/../openshift-templates/s2i-app-build/template-no-secrets.json"
    params: "{{ inventory_dir }}/../params/noun-app/build"
    namespace: rhoar-vertx-ci-cd
  - name: insult-app-build
    template: "{{ inventory_dir }}/../openshift-templates/s2i-app-build/template-no-secrets.json"
    params: "{{ inventory_dir }}/../params/insult-app/build"
    namespace: rhoar-vertx-ci-cd
  - name: ui-app-build
    template: "{{ inventory_dir }}/../openshift-templates/s2i-app-build/template-no-secrets.json"
    params: "{{ inventory_dir }}/../params/ui-app/build"
    namespace: rhoar-vertx-ci-cd
- object: dev-stage
  content:
  - name: apps-config
    template: "{{ inventory_dir }}/../openshift-templates/insult-configmaps/template.yaml"
    params: "{{ inventory_dir }}/../params/insult-configmap/deploy"
    namespace: rhoar-vertx-dev
    tags:
    - apps-config
  - name: adjective-app
    template: "{{ inventory_dir }}/../openshift-templates/vertx-app-k8s-api/template.yaml"
    params: "{{ inventory_dir }}/../params/adjective-app/deploy_dev"
    namespace: rhoar-vertx-dev
    tags:
    - adjective-app
  - name: noun-app
    template: "{{ inventory_dir }}/../openshift-templates/vertx-app-k8s-api/template.yaml"
    params: "{{ inventory_dir }}/../params/noun-app/deploy_dev"
    namespace: rhoar-vertx-dev
    tags:
    - noun-app
  - name: insult-app
    template: "{{ inventory_dir }}/../openshift-templates/vertx-app-k8s-api/template.yaml"
    params: "{{ inventory_dir }}/../params/insult-app/deploy_dev"
    namespace: rhoar-vertx-dev
    tags:
    - insult-app
  - name: ui-app
    template: "{{ inventory_dir }}/../openshift-templates/vertx-app-k8s-api/template.yaml"
    params: "{{ inventory_dir }}/../params/ui-app/deploy_dev"
    namespace: rhoar-vertx-dev
    tags:
    - ui-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/ui-app/fabric8_dev"
    namespace: rhoar-vertx-dev
    tags:
    - app
  - name: default-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/k8s-configmap-api-rolebinding/template.yaml"
    params: "{{ inventory_dir }}/../params/rolebindings/dev"
    namespace: rhoar-vertx-dev
    tags:
    - app
- object: demo-stage
  content:
  - name: apps-config
    template: "{{ inventory_dir }}/../openshift-templates/insult-configmaps/template.yaml"
    namespace: rhoar-vertx-demo
    params: "{{ inventory_dir }}/../params/insult-configmap/deploy"
    tags:
    - apps-config
  - name: adjective-app
    template: "{{ inventory_dir }}/../openshift-templates/vertx-app-k8s-api/template.yaml"
    params: "{{ inventory_dir }}/../params/adjective-app/deploy_demo"
    namespace: rhoar-vertx-demo
    tags:
    - adjective-app
  - name: noun-app
    template: "{{ inventory_dir }}/../openshift-templates/vertx-app-k8s-api/template.yaml"
    params: "{{ inventory_dir }}/../params/noun-app/deploy_demo"
    namespace: rhoar-vertx-demo
    tags:
    - noun-app
  - name: insult-app
    template: "{{ inventory_dir }}/../openshift-templates/vertx-app-k8s-api/template.yaml"
    params: "{{ inventory_dir }}/../params/insult-app/deploy_demo"
    namespace: rhoar-vertx-demo
    tags:
    - insult-app
  - name: ui-app
    template: "{{ inventory_dir }}/../openshift-templates/vertx-app-k8s-api/template.yaml"
    params: "{{ inventory_dir }}/../params/ui-app/deploy_demo"
    namespace: rhoar-vertx-demo
    tags:
    - ui-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/ui-app/fabric8_demo"
    namespace: rhoar-vertx-demo
    tags:
    - app
  - name: default-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/k8s-configmap-api-rolebinding/template.yaml"
    params: "{{ inventory_dir }}/../params/rolebindings/demo"
    namespace: rhoar-vertx-demo
    tags:
    - app
